### ISSUE TITLE
Your ref code doesnt work 

### ISSUE THREAD

**Issue by shaonturaj** [recitativonika/lisk-auto#1]
![Screenshot 2024-12-01 031422](https://github.com/user-attachments/assets/544ab78f-83d8-4eee-88eb-f8bc02cf2475)

**Comment by recitativonika** [comment]
hmmm it should work.
Try to change to Lisk (mainnet) network in top right corner before enter the reff code, let me know if it working or not.
and, it's case sensitive. Make sure you put exactly same
```bash
oHRCaR
```
