### ISSUE TITLE
Invalid Length pkeys 

### ISSUE THREAD

**Issue by shaonturaj** [recitativonika/lisk-auto#2]
![Screenshot 2024-12-06 132034](https://github.com/user-attachments/assets/b67e4638-ea94-440f-9174-815540210cc4)

I have used MM private key .  and it says like this

**Comment by recitativonika** [comment]
Delete this text
```
privkey1
privkey2
```
In the priv.txt and then paste your private key in there.

**Comment by shaonturaj** [comment]
![Screenshot_20241206_135526_Termius](https://github.com/user-attachments/assets/1e109923-79ef-4344-b3e2-85136e59da09)

Check this.. Correct?

**Comment by shaonturaj** [comment]
Oh i see.. I had to insert private key on key.txt file 

Not on priv.txt that's why it wasnt not working. Now after inserting on key.txt its working. Thanks

**Comment by recitativonika** [comment]
Great, sorry I say wrong file text.
