### ISSUE TITLE
Nonce Check SS

### ISSUE THREAD

**Issue by shaonturaj** [recitativonika/lisk-auto#3]
![Screenshot_20241212_175348_Termius](https://github.com/user-attachments/assets/a736e84b-fe9f-48a1-99c2-7bc7c2bf7998)

Encountering this issue

**Comment by recitativonika** [comment]
Can you try rerun again after couple minute?

**Comment by shaonturaj** [comment]
Waited 5 hrs and still same :(

**Comment by recitativonika** [comment]
> Waited 5 hrs and still same :(

do you stop the script first and rerun or you just let the script run for 5 hour? if you not close/stop the script and run again, please try it first.

I test the script it should work
![image](https://github.com/user-attachments/assets/f23920f8-cfd3-4f5f-b81d-4fa8cbff0ab6)

If you still have nonce error after stop the script and running again, please let me know. I will add auto change nonce later, maybe

**Comment by shaonturaj** [comment]
I had stopped the bot for 5 hours and now i have started it again and its showing same error about nonce :(

**Comment by recitativonika** [comment]
I will make quick change about nonce detection, I don't know it will be fixed or not, if it still have problem please let me know again and I will trying fix tomorrow. Wait a moment!

**Comment by recitativonika** [comment]
I already make small changes to script, please pull the repo again!

**Comment by shaonturaj** [comment]
Woah!  You are insane mate!  Its working perfectly now <3 Thank you
