### ISSUE TITLE
Weekly Streak not count

### ISSUE THREAD

**Issue by Araara7** [recitativonika/lisk-auto#4]
Hello sis, why weekly streak not count ?

![image](https://github.com/user-attachments/assets/66928ceb-91bf-455e-aea9-d092fd8408bc)

**Comment by recitativonika** [comment]
Hmm I not really sure because it is server side detection. Maybe this is their server problem. Try ask the project team

**Comment by recitativonika** [comment]
I can confirm this is problem from them, wait till they fix it
![image](https://github.com/user-attachments/assets/a205c5aa-b1d9-479e-892a-042887c08aef)

**Comment by Araara7** [comment]
Aaah okaay sis, big thanks for feedback :)
